new Schema("farmersdelight:cooking")
	.simpleKey("result", "outputItem")
	.simpleKey("ingredients", "inputItemArray")
	.simpleKey("container", "inputItem", null)
	.simpleKey("cookingtime", "intNumber", 200)
	.simpleKey("experience", "floatNumber", 1.0)
	.simpleKey("recipe_book_tab", "nonBlankString", null)

new Schema("farmersdelight:cutting")
	.simpleKey("result", "outputItemArray")
	.simpleKey("ingredients", "inputItemArray")
	.dynamicKey((component, builder) => {
		return component.get("inputItem")()
			.or(new builder(2)
				.add(component.get("nonBlankString")().key("type"))
				.add(component.get("nonBlankString")().key("action"))
				.inputRole())
			.key("tool")
	})