StartupEvents.registry("block",event => {
    
    event.create("cmc:creative_fiuld_tank","basic")
    .model("cmc:block/creative_fiuld_tank")
    .hardness(5)
    .requiresTool(true)
    .tagBlock("create:wrench_pickup")
    .tagBlock('minecraft:needs_iron_tool')
    .tagBlock('minecraft:mineable/pickaxe')
    .soundType(SoundType.METAL)

    event.create("cmc:me_equipment_casing","basic")
    .model("cmc:block/me_equipment_casing")
    .hardness(5)
    .requiresTool(true)
    .tagBlock("create:wrench_pickup")
    .tagBlock('minecraft:needs_iron_tool')
    .tagBlock('minecraft:mineable/pickaxe')
    .soundType(SoundType.METAL)

    event.create("cmc:me_machine_casing","basic")
    .textureAll("cmc:block/casing/me_equipment_casing/top")
    .hardness(5)
    .requiresTool(true)
    .tagBlock("create:wrench_pickup")
    .tagBlock('minecraft:needs_iron_tool')
    .tagBlock('minecraft:mineable/pickaxe')
    .soundType(SoundType.METAL)
})