ServerEvents.recipes(event => {
    event.remove({ output: 'extendedcrafting:black_iron_slate' })
    event.remove({ output: 'extendedcrafting:black_iron_nugget' })
    event.remove({ output: 'extendedcrafting:black_iron_ingot' })
    event.remove({ output: 'ae2:black_lumen_paint_ball' })
    event.remove({ output: 'sophisticatedbackpacks:stack_upgrade_tier_4' })
    event.remove({ output: 'appliedcreate:me_gearbox' })
    event.remove({ input: 'appliedcreate:advanced_stress_processor' })
    event.remove({ input: 'appliedcreate:stress_processor' })
    event.remove({ input: 'appliedcreate:andesite_stress_cell_housing' })
    event.remove({ input: 'appliedcreate:brass_stress_cell_housing' })
    event.remove({ output: 'appliedcreate:andesite_stress_cell_housing' })
    /*event.remove({ output: 'appliedcreate:brass_stress_cell_housing' })*/
    event.remove({ output: 'expatternprovider:ex_drive' })
    event.remove({ output: 'minecraft:furnace' })
    /*整活用
    event.remove({output:'create:encased_fan'})
    event.remove({output:'create:mechanical_mixer'})
    event.remove({output:'create:millstone'})
    event.remove({output:'create:speedometer'})
    event.remove({output:'create:empty_blaze_burner'})
    event.remove({output:'create:mechanical_saw'})
    */
    event.remove({ id: 'create:crafting/materials/andesite_alloy' })
    event.remove({ output: 'chunkbychunk:worldcore' })
    event.remove({ output: 'ae2:fluix_upgrade_smithing_template' })
    event.remove({ output: 'thermal_extra:augment_smithing_upgrade' })
    event.remove({ output: 'chunkbychunk:worldshard' })
    event.remove({ output: 'chunkbychunk:worldcrystal' })
    event.remove({ id: "create:mixing/brass_ingot" })
    event.remove({ output: "create:brass_hand" })
    event.remove({ id: "create:crafting/materials/rose_quartz" })
    event.remove({ output: 'create:electron_tube' })
    event.remove({ output: 'appliedcreate:advanced_stress_circuit_board' })
    event.remove({ output: 'appliedcreate:stress_circuit_board' })
    event.remove({ output: "thermal:machine_frame" })
})